# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NqU5E_-ygUQIHiTG7uCM8Fy_16tYteeS

# Assignment 1
"""

array = [2, 5, 8, 11, 3, 14, 7, 9, 6, 13]

for num in array:
  if num % 2 == 0:
    print(num, "is even")
  else:
    print(num, "is odd")

"""# Assignment 2

"""

def process_scores(scores):

  average = sum(scores) / len(scores)
  highest = max(scores)
  lowest = min(scores)

  letter_grades = []
  for score in scores:
    if score >= 90:
      grade = 'A'
    elif score >= 80:
      grade = 'B'
    elif score >= 70:
      grade = 'C'
    elif score >= 60:
      grade = 'D'
    else:
      grade = 'F'
    letter_grades.append(grade)

  return {
      'average': average,
      'highest': highest,
      'lowest': lowest,
      'letter_grades': letter_grades
  }

scores = [85, 92, 78, 65, 55, 80]
result = process_scores(scores)
print(result)